services:

  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8010:8000"
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 3s
      timeout: 5s
      retries: 10
    volumes:
      - ./db_data:/var/lib/postgresql/data
